# Generated by Django 2.2a1 on 2019-01-18 16:15

import apps.trade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('share', models.BooleanField(default=False, verbose_name='share')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trader_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('G', 'Gain'), ('L', 'Loss')], default='G', max_length=10, verbose_name='outcome')),
                ('pips', models.SmallIntegerField(verbose_name='pips')),
                ('share', models.BooleanField(default=False, verbose_name='share')),
                ('traded', models.DateTimeField(auto_now=True)),
                ('chart_before', models.FileField(blank=True, help_text='Attach Before Chart', upload_to=apps.trade.models.file_upload_to_dispatcher, verbose_name='chart before')),
                ('chart_after', models.FileField(blank=True, help_text='Attach After Chart', upload_to=apps.trade.models.file_upload_to_dispatcher, verbose_name='chart after')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.Pair')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.Strategy')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trader_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('share', models.BooleanField(default=False, verbose_name='share')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trader_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('posted', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.Trade')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('statement', models.TextField(verbose_name='statement')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pairs', models.ManyToManyField(blank=True, to='trade.Pair')),
                ('strategies', models.ManyToManyField(blank=True, to='trade.Strategy')),
            ],
        ),
    ]
