# Generated by Django 2.2a1 on 2019-01-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_trades', to='trade.Strategy'),
        ),
    ]
