# Generated by Django 2.2a1 on 2019-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190118_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.CharField(choices=[('L', 'Long'), ('S', 'Short')], default='L', max_length=10, verbose_name='position'),
        ),
    ]
