# Generated by Django 2.2a1 on 2019-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_trade_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='outcome',
            field=models.CharField(blank=True, choices=[('G', 'Gain'), ('L', 'Loss')], default='G', max_length=10, null=True, verbose_name='outcome'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pips',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='pips'),
        ),
    ]
