# Generated by Django 2.2a1 on 2019-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190119_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
