# Generated by Django 2.2a1 on 2019-01-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_trade_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trader_portfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
